apiVersion: apps/v1
kind: Deployment
 metadata :
  - name: ngnix-deployment
    labels:
     app: nginx
     spec:
      replicas: 3
      selector:
      matchLabels:
      app: nginx
      template:
      metadata:
      labels:
        app: nginx
      spec:
      containers:
      - name: nginx
      image: ademkoraani/github:latest 
        ports:
        - containerPort: 80
